version: "3.8"

services:
  api:
    image: milodorosario/pirtolx-api:latest
    container_name: pirtolx-api
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8055:8055"

  redis:
    image: redis:7-alpine
    container_name: pirtolx-api-redis
    restart: always
    ports:
      - "6379:6379"
